Update CHEBI import
geneontology/go-ontology pull request #17555
Opened 2019-07-01 13:18 UTC by ontobot

I've updated the CHEBI import.

2019-07-01 13:31 UTC, balhoff commented
I'm pasting this here, because @ontobot is having some issues with the message size.

# Ontology comparison

## Old
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2019-07-01/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-chebi-import/go-ontology/src/ontology/reasoned-prev.owl`

## New
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2019-07-01/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-chebi-import/go-ontology/src/ontology/reasoned.owl`

### Ontology imports 



### Ontology annotations 



### (25S)-Delta(4)-dafachronate metabolic process `http://purl.obolibrary.org/obo/GO_1902057`
#### Removed
- [(25S)-Delta(4)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902057) SubClassOf [steroid metabolic process](http://purl.obolibrary.org/obo/GO_0008202) 

- [(25S)-Delta(4)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902057) SubClassOf [hormone metabolic process](http://purl.obolibrary.org/obo/GO_0042445) 

- [(25S)-Delta(4)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902057) SubClassOf [monocarboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0032787) 

- [(25S)-Delta(4)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902057) SubClassOf [cellular ketone metabolic process](http://purl.obolibrary.org/obo/GO_0042180) 

#### Added
- [(25S)-Delta(4)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902057) SubClassOf [carboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0019752) 


### (25S)-Delta(7)-dafachronate metabolic process `http://purl.obolibrary.org/obo/GO_1902056`
#### Removed
- [(25S)-Delta(7)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902056) SubClassOf [monocarboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0032787) 

- [(25S)-Delta(7)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902056) SubClassOf [steroid metabolic process](http://purl.obolibrary.org/obo/GO_0008202) 

- [(25S)-Delta(7)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902056) SubClassOf [cellular ketone metabolic process](http://purl.obolibrary.org/obo/GO_0042180) 

- [(25S)-Delta(7)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902056) SubClassOf [hormone metabolic process](http://purl.obolibrary.org/obo/GO_0042445) 

#### Added
- [(25S)-Delta(7)-dafachronate metabolic process](http://purl.obolibrary.org/obo/GO_1902056) SubClassOf [carboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0019752) 


### (2S)-homocitric acid `http://purl.obolibrary.org/obo/CHEBI_143966`

#### Added
- [(2S)-homocitric acid](http://purl.obolibrary.org/obo/CHEBI_143966) SubClassOf [homocitric acid](http://purl.obolibrary.org/obo/CHEBI_17852) 


### (R)-2-hydroxy-alpha-linolenic acid biosynthetic process `http://purl.obolibrary.org/obo/GO_1902609`
#### Removed
- [(R)-2-hydroxy-alpha-linolenic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_1902609) SubClassOf [long-chain fatty acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0042759) 

- [(R)-2-hydroxy-alpha-linolenic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_1902609) SubClassOf [unsaturated fatty acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0006636) 

#### Added
- [(R)-2-hydroxy-alpha-linolenic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_1902609) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

- [(R)-2-hydroxy-alpha-linolenic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_1902609) SubClassOf [organic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0016053) 


### (R)-mandelate catabolic process to benzoate `http://purl.obolibrary.org/obo/GO_0019597`
#### Removed
- [(R)-mandelate catabolic process to benzoate](http://purl.obolibrary.org/obo/GO_0019597) SubClassOf [organic cyclic compound biosynthetic process](http://purl.obolibrary.org/obo/GO_1901362) 

- [(R)-mandelate catabolic process to benzoate](http://purl.obolibrary.org/obo/GO_0019597) SubClassOf [antibiotic biosynthetic process](http://purl.obolibrary.org/obo/GO_0017000) 

- [(R)-mandelate catabolic process to benzoate](http://purl.obolibrary.org/obo/GO_0019597) SubClassOf [aromatic compound biosynthetic process](http://purl.obolibrary.org/obo/GO_0019438) 



### (R)-mevalonic acid biosynthetic process `http://purl.obolibrary.org/obo/GO_1901737`
#### Removed
- [(R)-mevalonic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_1901737) SubClassOf [monocarboxylic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0072330) 

#### Added
- [(R)-mevalonic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_1901737) SubClassOf [organic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0016053) 


### (R)-mevalonic acid catabolic process `http://purl.obolibrary.org/obo/GO_1901736`
#### Removed
- [(R)-mevalonic acid catabolic process](http://purl.obolibrary.org/obo/GO_1901736) SubClassOf [monocarboxylic acid catabolic process](http://purl.obolibrary.org/obo/GO_0072329) 

#### Added
- [(R)-mevalonic acid catabolic process](http://purl.obolibrary.org/obo/GO_1901736) SubClassOf [organic acid catabolic process](http://purl.obolibrary.org/obo/GO_0016054) 


### (R)-mevalonic acid metabolic process `http://purl.obolibrary.org/obo/GO_1901735`
#### Removed
- [(R)-mevalonic acid metabolic process](http://purl.obolibrary.org/obo/GO_1901735) SubClassOf [monocarboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0032787) 

#### Added
- [(R)-mevalonic acid metabolic process](http://purl.obolibrary.org/obo/GO_1901735) SubClassOf [organic acid metabolic process](http://purl.obolibrary.org/obo/GO_0006082) 


### (S)-reticuline metabolic process `http://purl.obolibrary.org/obo/GO_1901010`
#### Removed
- [(S)-reticuline metabolic process](http://purl.obolibrary.org/obo/GO_1901010) SubClassOf [ammonium ion metabolic process](http://purl.obolibrary.org/obo/GO_0097164) 



### (Z)-3-aminoperacrylic acid `http://purl.obolibrary.org/obo/CHEBI_59892`

#### Added
- [(Z)-3-aminoperacrylic acid](http://purl.obolibrary.org/obo/CHEBI_59892) SubClassOf [enamine](http://purl.obolibrary.org/obo/CHEBI_47989) 


### 1,2-diacyl-sn-glycero-3-phosphocholine metabolic process `http://purl.obolibrary.org/obo/GO_0006653`
#### Removed
- [1,2-diacyl-sn-glycero-3-phosphocholine metabolic process](http://purl.obolibrary.org/obo/GO_0006653) SubClassOf [phosphatidylcholine metabolic process](http://purl.obolibrary.org/obo/GO_0046470) 

#### Added
- [1,2-diacyl-sn-glycero-3-phosphocholine metabolic process](http://purl.obolibrary.org/obo/GO_0006653) SubClassOf [organic substance metabolic process](http://purl.obolibrary.org/obo/GO_0071704) 

- [1,2-diacyl-sn-glycero-3-phosphocholine metabolic process](http://purl.obolibrary.org/obo/GO_0006653) SubClassOf [ammonium ion metabolic process](http://purl.obolibrary.org/obo/GO_0097164) 


### 1,6-anhydro-N-acetyl-beta-muramic acid catabolic process `http://purl.obolibrary.org/obo/GO_0097175`
#### Removed
- [1,6-anhydro-N-acetyl-beta-muramic acid catabolic process](http://purl.obolibrary.org/obo/GO_0097175) SubClassOf [carbohydrate derivative catabolic process](http://purl.obolibrary.org/obo/GO_1901136) 



### 1,6-anhydro-N-acetyl-beta-muramic acid metabolic process `http://purl.obolibrary.org/obo/GO_0097174`
#### Removed
- [1,6-anhydro-N-acetyl-beta-muramic acid metabolic process](http://purl.obolibrary.org/obo/GO_0097174) SubClassOf [carbohydrate derivative metabolic process](http://purl.obolibrary.org/obo/GO_1901135) 



### 1-aminocyclopropane-1-carboxylate biosynthetic process `http://purl.obolibrary.org/obo/GO_0042218`
#### Removed
- [1-aminocyclopropane-1-carboxylate bi [...]

2019-07-01 13:31 UTC, balhoff commented
### codeine metabolic process `http://purl.obolibrary.org/obo/GO_2001291`
#### Removed
- [codeine metabolic process](http://purl.obolibrary.org/obo/GO_2001291) SubClassOf [ammonium ion metabolic process](http://purl.obolibrary.org/obo/GO_0097164) 



### coenzyme B biosynthetic process `http://purl.obolibrary.org/obo/GO_0019298`
#### Removed
- [coenzyme B biosynthetic process](http://purl.obolibrary.org/obo/GO_0019298) SubClassOf [monocarboxylic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0072330) 



### coenzyme B metabolic process `http://purl.obolibrary.org/obo/GO_0019297`
#### Removed
- [coenzyme B metabolic process](http://purl.obolibrary.org/obo/GO_0019297) SubClassOf [monocarboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0032787) 

- [coenzyme B metabolic process](http://purl.obolibrary.org/obo/GO_0019297) SubClassOf [phosphorus metabolic process](http://purl.obolibrary.org/obo/GO_0006793) 



### coenzyme gamma-F420-2 biosynthetic process `http://purl.obolibrary.org/obo/GO_2001121`
#### Removed
- [coenzyme gamma-F420-2 biosynthetic process](http://purl.obolibrary.org/obo/GO_2001121) SubClassOf [tricarboxylic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0072351) 



### coenzyme gamma-F420-2 metabolic process `http://purl.obolibrary.org/obo/GO_0052649`
#### Removed
- [coenzyme gamma-F420-2 metabolic process](http://purl.obolibrary.org/obo/GO_0052649) SubClassOf [tricarboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0072350) 



### copal-8-ol diphosphate(3-) biosynthetic process `http://purl.obolibrary.org/obo/GO_1902243`
#### Removed
- [copal-8-ol diphosphate(3-) biosynthetic process](http://purl.obolibrary.org/obo/GO_1902243) SubClassOf [diterpenoid biosynthetic process](http://purl.obolibrary.org/obo/GO_0016102) 

- [copal-8-ol diphosphate(3-) biosynthetic process](http://purl.obolibrary.org/obo/GO_1902243) SubClassOf [phospholipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008654) 

#### Added
- [copal-8-ol diphosphate(3-) biosynthetic process](http://purl.obolibrary.org/obo/GO_1902243) SubClassOf [organic substance biosynthetic process](http://purl.obolibrary.org/obo/GO_1901576) 


### copal-8-ol diphosphate(3-) catabolic process `http://purl.obolibrary.org/obo/GO_1902242`
#### Removed
- [copal-8-ol diphosphate(3-) catabolic process](http://purl.obolibrary.org/obo/GO_1902242) SubClassOf [phospholipid catabolic process](http://purl.obolibrary.org/obo/GO_0009395) 

- [copal-8-ol diphosphate(3-) catabolic process](http://purl.obolibrary.org/obo/GO_1902242) SubClassOf [diterpenoid catabolic process](http://purl.obolibrary.org/obo/GO_0016103) 

#### Added
- [copal-8-ol diphosphate(3-) catabolic process](http://purl.obolibrary.org/obo/GO_1902242) SubClassOf [organic substance catabolic process](http://purl.obolibrary.org/obo/GO_1901575) 


### copal-8-ol diphosphate(3-) metabolic process `http://purl.obolibrary.org/obo/GO_1902241`
#### Removed
- [copal-8-ol diphosphate(3-) metabolic process](http://purl.obolibrary.org/obo/GO_1902241) SubClassOf [diterpenoid metabolic process](http://purl.obolibrary.org/obo/GO_0016101) 

- [copal-8-ol diphosphate(3-) metabolic process](http://purl.obolibrary.org/obo/GO_1902241) SubClassOf [phospholipid metabolic process](http://purl.obolibrary.org/obo/GO_0006644) 

#### Added
- [copal-8-ol diphosphate(3-) metabolic process](http://purl.obolibrary.org/obo/GO_1902241) SubClassOf [phosphorus metabolic process](http://purl.obolibrary.org/obo/GO_0006793) 

- [copal-8-ol diphosphate(3-) metabolic process](http://purl.obolibrary.org/obo/GO_1902241) SubClassOf [organic substance metabolic process](http://purl.obolibrary.org/obo/GO_0071704) 


### creatine biosynthetic process `http://purl.obolibrary.org/obo/GO_0006601`
#### Removed
- [creatine biosynthetic process](http://purl.obolibrary.org/obo/GO_0006601) SubClassOf [monocarboxylic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0072330) 



### creatine metabolic process `http://purl.obolibrary.org/obo/GO_0006600`
#### Removed
- [creatine metabolic process](http://purl.obolibrary.org/obo/GO_0006600) SubClassOf [monocarboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0032787) 



### cspyrone B1 biosynthetic process `http://purl.obolibrary.org/obo/GO_1900802`
#### Removed
- [cspyrone B1 biosynthetic process](http://purl.obolibrary.org/obo/GO_1900802) SubClassOf [monocarboxylic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0072330) 

#### Added
- [cspyrone B1 biosynthetic process](http://purl.obolibrary.org/obo/GO_1900802) SubClassOf [organic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0016053) 


### cspyrone B1 catabolic process `http://purl.obolibrary.org/obo/GO_1900801`
#### Removed
- [cspyrone B1 catabolic process](http://purl.obolibrary.org/obo/GO_1900801) SubClassOf [monocarboxylic acid catabolic process](http://purl.obolibrary.org/obo/GO_0072329) 

#### Added
- [cspyrone B1 catabolic process](http://purl.obolibrary.org/obo/GO_1900801) SubClassOf [organic acid catabolic process](http://purl.obolibrary.org/obo/GO_0016054) 


### cspyrone B1 metabolic process `http://purl.obolibrary.org/obo/GO_1900800`
#### Removed
- [cspyrone B1 metabolic process](http://purl.obolibrary.org/obo/GO_1900800) SubClassOf [monocarboxylic acid metabolic process](http://purl.obolibrary.org/obo/GO_0032787) 

#### Added
- [cspyrone B1 metabolic process](http://purl.obolibrary.org/obo/GO_1900800) SubClassOf [organic acid metabolic process](http://purl.obolibrary.org/obo/GO_0006082) 


### cyanide biosynthetic process `http://purl.obolibrary.org/obo/GO_0046202`
#### Removed
- [cyanide biosynthetic process](http://purl.obolibrary.org/obo/GO_0046202) SubClassOf [organic substance biosynthetic process](http://purl.obolibrary.org/obo/GO_1901576) 



### cyanide catabolic process `http://purl.obolibrary.org/obo/GO_0019500`
#### Removed
- [cyanide catabolic process](http://purl.obolibrary.org/obo/GO_0019500) SubClassOf [organic substance catabolic process](http://purl.obolibrary.org/obo/GO_1901575) 



### cyanide metabolic process `http://purl.obolibrary.org/obo/GO_0019499`
#### Removed
- [cyanide metabolic process](http://purl.obolibrary.org/obo/GO_0019499) SubClassOf [organic substance metabolic process](http://purl.obolibrary.org/obo/GO_0071704) 



### cyanoamino acid metabolic process `http://purl.obolibrary.org/obo/GO_0033052`
#### Removed
- [cyanoamino acid metabolic process](http://purl.obolibrary.org/obo/GO_0033052) SubClassOf [cellular amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0006520) 

#### Added
- [cyanoamino acid metabolic process](http://purl.obolibrary.org/obo/GO_0033052) SubClassOf [organic acid metabolic process](http://purl.obolibrary.org/obo/GO_0006082) 


### cyclic 2,3-bisphospho-D-glycerate biosynthetic process `http://purl.obolibrary.org/obo/GO_1901369`
#### Removed
- [cyclic 2,3-bisphospho-D-glycerate biosynthetic process](http://purl.obolibrary.org/obo/GO_1901369) SubClassOf [aldonic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0046175) 



### cysteine biosynthetic process `http://purl.obolibrary.org/obo/GO_0019344`
#### Removed
- [cysteine biosynthetic process](http://purl.obolibrary.org/obo/GO_0019344) SubClassOf [sulfur amino acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0000097) 



### cysteine catabolic process `http://purl.obolibrary.org/obo/GO_0009093`
#### Removed
- [cysteine catabolic process](http://purl.obolibrary.org/obo/GO_0009093) SubClassOf [sulfur amino acid catabolic process](http://purl.obolibrary.org/obo/GO_0000098) 



### cysteine metabolic process `http://purl.obolibrary.org/obo/GO_0006534`
#### Removed
- [cysteine metabolic process](http://purl.obolibrary.org/obo/GO_0006534) SubClassOf [sulfur amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0000096) 



### daunorubicin metabolic process `http://purl.obolibrary.org/obo/GO_0044597`
 [...]

2019-07-01 13:52 UTC, ukemi commented
Looks like there are a few weird issues. See valine metabolic process and the 9-cis retinoic acid terms.

2019-07-03 14:35 UTC, balhoff requested changes
We need to find why there are such a huge number of deletions in the OWL file.

2019-07-03 15:19 UTC, balhoff commented
I think I see the problem here. @ontobot has been using an old version of owltools which doesn't have the update needed for the new primary_input relations.

2019-07-03 15:19 UTC, closed without merging

2019-07-03 15:39 UTC, ukemi commented
It might also be ignoring the GCIs for acid/base and charge states. Just a hint from looking at the file.