removed all 12 axioms using cofactor or coenzyme roles
geneontology/go-ontology pull request #17913
Opened 2019-09-25 21:24 UTC by krchristie

2019-09-25 21:27 UTC, krchristie commented
@balhoff - Here is my pull request with the cofactor & coenzyme role containing equivalence axioms removed in order to see what reasoning we lose when we take them out.

In the case of the transport terms, I have manually asserted an is_a parent in order to keep them under 'transport'.

2019-09-30 16:28 UTC, balhoff commented
@krchristie here is the diff of the reasoned file before and after your changes:

### 7,8-didemethyl-8-hydroxy-5-deazariboflavin biosynthetic process `http://purl.obolibrary.org/obo/GO_1901852`
#### Removed
- [7,8-didemethyl-8-hydroxy-5-deazariboflavin biosynthetic process](http://purl.obolibrary.org/obo/GO_1901852) SubClassOf [cofactor biosynthetic process](http://purl.obolibrary.org/obo/GO_0051188) 



### 7,8-didemethyl-8-hydroxy-5-deazariboflavin catabolic process `http://purl.obolibrary.org/obo/GO_1901851`
#### Removed
- [7,8-didemethyl-8-hydroxy-5-deazariboflavin catabolic process](http://purl.obolibrary.org/obo/GO_1901851) SubClassOf [cofactor catabolic process](http://purl.obolibrary.org/obo/GO_0051187) 



### 7,8-didemethyl-8-hydroxy-5-deazariboflavin metabolic process `http://purl.obolibrary.org/obo/GO_1901850`
#### Removed
- [7,8-didemethyl-8-hydroxy-5-deazariboflavin metabolic process](http://purl.obolibrary.org/obo/GO_1901850) SubClassOf [cofactor metabolic process](http://purl.obolibrary.org/obo/GO_0051186) 



### ATPase-coupled ferric-enterobactin transmembrane transporter activity `http://purl.obolibrary.org/obo/GO_0015624`
#### Removed
- [ATPase-coupled ferric-enterobactin transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015624) SubClassOf [cofactor transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051184) 



### ATPase-coupled vitamin B12 transmembrane transporter activity `http://purl.obolibrary.org/obo/GO_0015420`
#### Removed
- [ATPase-coupled vitamin B12 transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015420) SubClassOf [cofactor transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051184) 



### FAD transmembrane transport `http://purl.obolibrary.org/obo/GO_0035350`
#### Removed
- [FAD transmembrane transport](http://purl.obolibrary.org/obo/GO_0035350) SubClassOf [cofactor transport](http://purl.obolibrary.org/obo/GO_0051181) 



### FMN binding `http://purl.obolibrary.org/obo/GO_0010181`
#### Removed
- [FMN binding](http://purl.obolibrary.org/obo/GO_0010181) SubClassOf [coenzyme binding](http://purl.obolibrary.org/obo/GO_0050662) 

#### Added
- [FMN binding](http://purl.obolibrary.org/obo/GO_0010181) SubClassOf [cofactor binding](http://purl.obolibrary.org/obo/GO_0048037) 


### FMN transmembrane transporter activity `http://purl.obolibrary.org/obo/GO_0044610`
#### Removed
- [FMN transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0044610) SubClassOf [coenzyme transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051185) 



### L-ascorbic acid binding `http://purl.obolibrary.org/obo/GO_0031418`
#### Removed
- [L-ascorbic acid binding](http://purl.obolibrary.org/obo/GO_0031418) SubClassOf [coenzyme binding](http://purl.obolibrary.org/obo/GO_0050662) 



### L-ascorbic acid biosynthetic process `http://purl.obolibrary.org/obo/GO_0019853`
#### Removed
- [L-ascorbic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_0019853) SubClassOf [coenzyme biosynthetic process](http://purl.obolibrary.org/obo/GO_0009108) 



### L-ascorbic acid catabolic process `http://purl.obolibrary.org/obo/GO_0019854`
#### Removed
- [L-ascorbic acid catabolic process](http://purl.obolibrary.org/obo/GO_0019854) SubClassOf [coenzyme catabolic process](http://purl.obolibrary.org/obo/GO_0009109) 



### L-ascorbic acid metabolic process `http://purl.obolibrary.org/obo/GO_0019852`
#### Removed
- [L-ascorbic acid metabolic process](http://purl.obolibrary.org/obo/GO_0019852) SubClassOf [coenzyme metabolic process](http://purl.obolibrary.org/obo/GO_0006732) 



### L-ascorbic acid transmembrane transport `http://purl.obolibrary.org/obo/GO_0015882`
#### Removed
- [L-ascorbic acid transmembrane transport](http://purl.obolibrary.org/obo/GO_0015882) SubClassOf [coenzyme transport](http://purl.obolibrary.org/obo/GO_0051182) 



### L-ascorbic acid transmembrane transporter activity `http://purl.obolibrary.org/obo/GO_0015229`
#### Removed
- [L-ascorbic acid transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015229) SubClassOf [coenzyme transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051185) 



### NAD transmembrane transporter activity `http://purl.obolibrary.org/obo/GO_0051724`
#### Removed
- [NAD transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051724) SubClassOf [coenzyme transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051185) 

#### Added
- [NAD transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051724) SubClassOf [cofactor transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051184) 


### NAD transport `http://purl.obolibrary.org/obo/GO_0043132`
#### Removed
- [NAD transport](http://purl.obolibrary.org/obo/GO_0043132) SubClassOf [coenzyme transport](http://purl.obolibrary.org/obo/GO_0051182) 

#### Added
- [NAD transport](http://purl.obolibrary.org/obo/GO_0043132) SubClassOf [cofactor transport](http://purl.obolibrary.org/obo/GO_0051181) 


### S-adenosyl-L-methionine binding `http://purl.obolibrary.org/obo/GO_1904047`
#### Removed
- [S-adenosyl-L-methionine binding](http://purl.obolibrary.org/obo/GO_1904047) SubClassOf [coenzyme binding](http://purl.obolibrary.org/obo/GO_0050662) 



### S-adenosylhomocysteine catabolic process `http://purl.obolibrary.org/obo/GO_0019510`
#### Removed
- [S-adenosylhomocysteine catabolic process](http://purl.obolibrary.org/obo/GO_0019510) SubClassOf [cofactor catabolic process](http://purl.obolibrary.org/obo/GO_0051187) 



### S-adenosylhomocysteine metabolic process `http://purl.obolibrary.org/obo/GO_0046498`
#### Removed
- [S-adenosylhomocysteine metabolic process](http://purl.obolibrary.org/obo/GO_0046498) SubClassOf [cofactor metabolic process](http://purl.obolibrary.org/obo/GO_0051186) 



### acetyl-CoA binding `http://purl.obolibrary.org/obo/GO_1905502`
#### Removed
- [acetyl-CoA binding](http://purl.obolibrary.org/obo/GO_1905502) SubClassOf [coenzyme binding](http://purl.obolibrary.org/obo/GO_0050662) 



### acetyl-CoA transmembrane transport `http://purl.obolibrary.org/obo/GO_0035348`
#### Removed
- [acetyl-CoA transmembrane transport](http://purl.obolibrary.org/obo/GO_0035348) SubClassOf [acetyl-CoA transport](http://purl.obolibrary.org/obo/GO_0015876) 

#### Added
- [acetyl-CoA transmembrane transport](http://purl.obolibrary.org/obo/GO_0035348) SubClassOf [transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) some [acetyl-CoA](http://purl.obolibrary.org/obo/CHEBI_15351) 

- [acetyl-CoA transmembrane transport](http://purl.obolibrary.org/obo/GO_0035348) SubClassOf [fatty-acyl-CoA transport](http://purl.obolibrary.org/obo/GO_0015916) 


### aerobactin biosynthetic process `http://purl.obolibrary.org/obo/GO_0019270`
#### Removed
- [aerobactin biosynthetic process](http://purl.obolibrary.org/obo/GO_0019270) SubClassOf [cofactor biosynthetic process](http://purl.obolibrary.org/obo/GO_0051188) 



### aerobactin transport `http://purl.obolibrary.org/obo/GO_0019271`
#### Removed
- [aerobactin transport](http://purl.obolibrary.org/obo/GO_0019271) SubClassOf [cofactor transport](http://purl.obolibrary.org/obo/GO_0051181) 



### biopterin transmembrane transporter activity `http://purl.obolibrary.org/obo/GO_0015224`
#### Removed
- [biopterin transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015224) SubClassOf [coenzyme transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051185) 

#### Added
- [biopterin transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015224) SubClassOf [cofactor transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051184) 


### biopterin transport `http://purl.obolibrary.org/obo/GO_0015877`
#### Removed
- [biopterin transport](http://purl.obolibrary.org/obo/GO_0015877) SubClassOf [coenzyme transport](http://purl.obolibrary.org/obo/GO_0051182) [...]

2019-09-30 22:01 UTC, krchristie commented
There are 108 individual ontology terms that have relationships that were either **Removed** (all terms had at 1 `SubClassOf` relationship removed) or **Added** (12 GO terms had 1 or more `SubClassOf` relationship added) in the reasoned file as a result of removing the 12 equivalence axioms referencing either of these two roles:
- substance with cofactor role
- substance with coenzyme role

Of these 2 were the GOCHE terms that we are no longer referring to. Then there were the 12 terms from which the equivalence axioms were removed. Here is the table of those 2 GOCHE terms and 12 GO terms:

Type | Term | ID
-- | -- | --
GOCHE | substance with coenzyme role | GOCHE:23354
GOCHE | substance with cofactor role | GOCHE:23357
GO | cofactor binding | GO:0048037
GO | cofactor biosynthetic process | GO:0051188
GO | cofactor catabolic process | GO:0051187
GO | cofactor metabolic process | GO:0051186
GO | cofactor transmembrane transporter activity | GO:0051184
GO | cofactor transport | GO:0051181
GO | coenzyme binding | GO:0050662
GO | coenzyme biosynthetic process | GO:0009108
GO | coenzyme catabolic process | GO:0009109
GO | coenzyme metabolic process | GO:0006732
GO | coenzyme transmembrane transporter activity | GO:0051185
GO | coenzyme transport | GO:0051182

Then, there were an additional 94 GO terms that had a single `SubClassOf` relationship **Removed** from the reasoning. Of these removed relationships, 61 were relationships to some `cofactor` term and 30 were to some `coenzyme` term. Then there were 3 removals of `SubClassOf` relationships from 3 more specific terms. I'll address these 3 below when I address terms with **Added** `SubClassOf` relationships

Relationship removed | # GO terms |  
-- | -- | --
SubClassOf cofactor binding | 9 |  
SubClassOf cofactor metabolic process | 9 |  
SubClassOf cofactor biosynthetic process | 9 |  
SubClassOf cofactor catabolic process | 5 |  
SubClassOf cofactor transport | 11 |  
SubClassOf cofactor transmembrane transporter activity | 9 |  
SubClassOf regulation of cofactor metabolic process | 3 |  
SubClassOf negative regulation of cofactor metabolic process | 3 |  
SubClassOf positive regulation of cofactor metabolic process | 3 | 61
  |   |  
SubClassOf coenzyme binding | 6 |  
SubClassOf coenzyme metabolic process | 4 |  
SubClassOf coenzyme biosynthetic process | 3 |  
SubClassOf coenzyme catabolic process | 3 |  
SubClassOf coenzyme transport | 6 |  
SubClassOf coenzyme transmembrane transporter activity | 6 |  
SubClassOf negative regulation of coenzyme metabolic process | 1 |  
SubClassOf regulation of coenzyme metabolic process | 1 | 30
  |   |  
SubClassOf   S-adenosyl-L-methionine transmembrane transport | 1 |  
SubClassOf acetyl-CoA transport | 1 |  
SubClassOf coenzyme A transport | 1 | 3

Adding comment now, even though I'm not quite done... so I don't lose it before I come back to add the rest.

2019-10-01 01:25 UTC, krchristie commented
Here are the equivalence axioms of the three terms that are losing an inferred relationship that is true that I mentioned above:

**coenzyme A transmembrane transport (GO:0035349)**
> transport
>  and ('transports or maintains localization of' some 'coenzyme A')
>  and ('results in transport across' some membrane)

**mitochondrial S-adenosyl-L-methionine transmembrane transport (GO:1990543)**
> transport
>  and ('transports or maintains localization of' some S-adenosyl-L-methionine)
>  and ('results in transport across' some 'mitochondrial membrane')
>  and ('results in transport to from or in' some mitochondrion)



**acetyl-CoA transmembrane transport (GO:0035348)**
> transport
>  and ('transports or maintains localization of' some acetyl-CoA)
>  and ('results in transport across' some membrane)



Here are the equivalence axioms of two other transmembrane transport terms:

**ion transmembrane transport (GO:0034220)**
> transport
>  and ('transports or maintains localization of' some ion)
>  and ('results in transport across' some membrane)

This term **IS** classified under `ion transport` by an inferred `SubClassOf` relationship.


**FAD transmembrane transport (GO:0035350)**
> transport
>  and ('transports or maintains localization of' some FAD)
>  and ('results in transport across' some membrane)

This term is **NOT** classified under `FAD transport`. When you look under the term `organic ion transport`, `FAD transmembrane transport` and `FAD transport` are sibling terms at the same level.

Therefore, it seems that our reasoning is not robust about reasoning over compounds to be able to say that `x transmembrane transport` is a type of `x transport` where x is some compound.

So, while I think it is not great that these three terms lose an inferred relationship, I think that that issue is beyond the scope of the `cofactor/coenzyme` roles and should not prevent proceeding with committing the removal of the 12 equivalence axioms for `cofactor/coenzyme` roles. 

@ukemi @cmungall - Any objections to proceeding with this even though we will lose 3 true inferences?

2019-10-01 12:27 UTC, ukemi commented
Please proceed and open another ontology ticket for the ones that are not classified correctly. I suspect there is an issue with the chemicals used in the definitions of these terms. If you open a ticket, I will take a look.

2019-10-01 13:34 UTC, pgaudet commented
@krchristie 

The logical definition of FAD transport is
'coenzyme transport'
 and ('transports or maintains localization of' some FAD)

for FAD transmembrane transport to be asserted as a child we need to replace 
'coenzyme transport' -> transport

Thanks, 
Pascale

2019-10-01 13:56 UTC, ukemi commented
I suspect they will all be similar to this. Looks like you are already looking into it @gaudet, so @krchristie should assign the ticket to you.

2019-10-01 15:18 UTC, krchristie commented
> I suspect they will all be similar to this. Looks like you are already looking into it @pgaudet , so @krchristie should assign the ticket to you.

Thanks @pgaudet for pointing out the issue with the equivalence axiom of `FAD transport`. With respect to changing these axioms, I think that's within the scope of the ChEBI roles project, so I will assign that ticket to myself.

However, the lack of classification of `x transmembrane transport` terms as types of `x transport` terms where x is some compound, may or may not be related to the `cofactor` role as the classification issue exists in the current updated master version of the ontology where I have not removed the `cofactor/coenzyme` roles.

![FADtransportVsTransmembrane](https://user-images.githubusercontent.com/10533218/65975135-04fa1f80-e423-11e9-9d66-dbd6a3d5f61b.jpg)

But one step at a time, 

- I'll proceed with the ticket to remove the 12 equivalence axioms using `cofactor/coenzyme` roles
- I'll make a ticket to change the equivalence axiom of `FAD transport` to see if it fixes the classification of the `FAD transmembrane transport` term.
- Depending on what happens there, I'll make a ticket about the lack of automatic classification of `x transmembrane transport` terms as types of `x transport` terms where x is some compound

2019-10-01 15:35 UTC, ukemi commented
We should probably start commenting in the ticket instead of in the pull request. But one thing this points out is to check to see where the relations to role terms have been asserted in the ontology. It might lead to weirdness when we pull out the inferences.

2019-10-02 03:55 UTC, cmungall requested changes
Wait, I don't think we want to lose all axiomatization. These terms follow a common structure, we want a DP for them and do have logical definitions. We want to infer trivial things like cofactor biosynthesis is-a cofactor metabolism. We just don't want to use chebi's structure->role links that's all

2019-10-02 21:48 UTC, krchristie commented
> Wait, I don't think we want to lose all axiomatization. These terms follow a common structure, we want a DP for them and do have logical definitions. We want to infer trivial things like cofactor biosynthesis is-a cofactor metabolism. We just don't want to use chebi's structure->role links that's all

We are not losing the fact that ` cofactor biosynthesis is-a cofactor metabolism`. Looking at the ontology from BEFORE I did anything, this info is NOT derived from axiomatization, but from direct assertions. Here are the stanzas (pruned to remove defs, ids, & synonyms) for `cofactor catabolic process` and `cofactor metabolic process` which contain both direct is_a assertions  (bold) as well as an equivalence axiom (italics) specifying the primary input. Removing the equivalence axiom does not affect the is_a assertions.

> [Term]
> id: GO:0051187
> name: cofactor catabolic process
> namespace: biological_process
> **is_a: GO:0044248 ! cellular catabolic process**
> **is_a: GO:0051186 ! cofactor metabolic process**
> _intersection_of: GO:0009056 ! catabolic process_
> _intersection_of: has_primary_input GOCHE:23357 ! substance with cofactor role_
>
> [Term]
> id: GO:0051188
> name: cofactor biosynthetic process
> namespace: biological_process
> **is_a: GO:0044249 ! cellular biosynthetic process**
> **is_a: GO:0051186 ! cofactor metabolic process**
> _intersection_of: GO:0009058 ! biosynthetic process_
> _intersection_of: has_primary_output GOCHE:23357 ! substance with cofactor role_

In the sampling of terms I have looked at (several pruned stanzas below), I do not see any terms where the relationship between `x catabolic/biosynthetic process` terms and `x metabolic process` terms is axiomitized. In all cases I have looked at, these relationships are directly asserted. When `x catabolic/biosynthetic process` terms are axiomitized, it is to usually to specify the input compound (see `macromolecule catabolic process` below) or occasionally to specify some other property but I can't find the one axiom I've seen that wasn't a chemical input of some kind right now. 

If it is possible to "**_infer trivial things like cofactor biosynthesis is-a cofactor metabolism_**", I do not see how to do it in the current ontology. Thus I am inclined to think that this is outside the scope of the ChEBI roles project and should not be part of this ticket.

> [Term]
> id: GO:0009056
> name: catabolic process
> namespace: biological_process
> **is_a: GO:0008152 ! metabolic process**
>
> [Term]
> id: GO:0009057
> name: macromolecule catabolic process
> namespace: biological_process
> _intersection_of: GO:0009056 ! catabolic process_
> _intersection_of: has_primary_input CHEBI:33694 ! biomacromolecule_
>
> [Term]
> id: GO:0009058
> name: biosynthetic process
> namespace: biological_process
> **is_a: GO:0008152 ! metabolic process**
>
> [Term]
> id: GO:0009059
> name: macromolecule biosynthetic process
> namespace: biological_process
> **is_a: GO:0043170 ! macromolecule metabolic process**
> **is_a: GO:1901576 ! organic substance biosynthetic process**
> _intersection_of: GO:0009058 ! biosynthetic process_
> _intersection_of: has_primary_output CHEBI:33694 ! biomacromolecule_
>
> [Term]
> id: GO:0044237
> name: cellular metabolic process
> namespace: biological_process
> **is_a: GO:0008152 ! metabolic process**
> **is_a: GO:0009987 ! cellular process**
>
> [Term]
> id: GO:0044248
> name: cellular catabolic process
> namespace: biological_process
> **is_a: GO:0009056 ! catabolic process**
> **is_a: GO:0044237 ! cellular metabolic process**
>
> [Term]
> id: GO:0044249
> name: cellular biosynthetic process
> namespace: biological_process
> **is_a: GO:0009058 ! biosynthetic process**
> **is_a: GO:0044237 ! cellular metabolic process**

2020-05-07 17:04 UTC, closed without merging