Create mf_binding.yaml
geneontology/go-ontology pull request #20321
Opened 2020-11-10 08:04 UTC by pgaudet

2020-11-10 16:47 UTC, cmungall commented on src/design_patterns/mf_binding.yaml
> +pattern_name: 'activator_activity'
oops!

2020-11-10 16:48 UTC, cmungall commented on src/design_patterns/mf_binding.yaml
> +data_list_vars:
@balhoff do we need all this boilerplate? can we not simplify these like we have e.g. for mondo?

2020-11-10 17:07 UTC, balhoff commented on src/design_patterns/mf_binding.yaml
> +data_list_vars:
No, we don't need the boilerplate. That is a holdover from the old patterns David had made.

2020-11-11 07:37 UTC, pgaudet commented
Is this better ? I removed both 'boiler plate' sections. I can remove from all design pattern files, if that's OK.

2020-11-11 19:38 UTC, balhoff requested changes

2020-11-11 19:38 UTC, balhoff commented on src/design_patterns/mf_binding.yaml
> +  has_input: %s
Instead of `%s` here, you need to put the type, e.g. `"'molecular_function'"`

2020-11-11 19:38 UTC, balhoff commented on src/design_patterns/mf_binding.yaml
> +  text: "%s binding"
Need a `vars:` list.

2020-11-11 19:38 UTC, balhoff commented on src/design_patterns/mf_binding.yaml
> +  text: "Binding to a %s."
Need a `vars:` list.

2020-11-11 19:38 UTC, balhoff commented on src/design_patterns/mf_binding.yaml
> +  text: "'binding' has input some %s"
Need a `vars:` list.

2020-11-11 19:38 UTC, balhoff commented on src/design_patterns/mf_binding.yaml
> +  text: "'binding' has input some %s"
Some syntax fixes for expression:

`"'binding' and ('has input' some %s)"`

2020-11-12 15:06 UTC, merged