taxon constraints for echolocation
geneontology/go-ontology pull request #21679
Opened 2021-06-22 21:47 UTC by cmungall

2021-06-23 01:14 UTC, balhoff requested changes
Technically looks good, but Wikipedia says there is echolocation in birds: https://en.wikipedia.org/wiki/Animal_echolocation#Oilbirds_and_swiftlets

2021-06-23 12:20 UTC, ukemi commented
I'm almost certain cave swiftlets and oil birds echolocate. A member of my thesis committee worked on them.

2021-06-23 14:01 UTC, balhoff approved these changes

2021-06-23 14:01 UTC, merged

2021-06-24 03:31 UTC, cmungall commented
Cool!

On Wed, Jun 23, 2021, 05:20 David Hill ***@***.***> wrote:

> I'm almost certain cave swiftlets and oil birds echolocate. A member of my
> thesis committee worked on them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geneontology/go-ontology/pull/21679#issuecomment-866787490>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAMMOL7EWYQPQRLBT5BK63TUHGPXANCNFSM47EQ6GCQ>
> .
>