Added LDs. #26444
geneontology/go-ontology pull request #26526
Opened 2023-11-30 00:32 UTC by raymond91125

2023-11-30 06:18 UTC, pgaudet requested changes
HI @raymond91105 

Since the proton does not bind to the channel, it is not an activator. 

You need to use genera = pH-gated monoatomic ion channel; 
primary inputs are OK. 

Thanks, Pascale

2023-12-04 17:24 UTC, raymond91125 commented
@pgaudet please review and approve changes if OK. thanks.

2023-12-04 17:31 UTC, pgaudet approved these changes

2023-12-04 17:31 UTC, pgaudet commented
Looks good!

2023-12-04 17:33 UTC, merged