Create symbiont_mediated_suppression_of_host_process
geneontology/go-ontology pull request #28797
Opened 2024-08-29 15:01 UTC by pgaudet

2024-08-30 16:27 UTC, balhoff requested changes

2024-08-30 16:27 UTC, balhoff commented on src/design_patterns/symbiont_mediated_suppression_of_host_process
> +     text: "symbiont-modulated suppression of host %s"
@pgaudet should it be "symbiont-mediated" instead of modulated?

2024-08-30 16:27 UTC, balhoff commented on src/design_patterns/symbiont_mediated_suppression_of_host_process
> +  entity: Thing
Can this be constrained to 'biological process'?

2024-09-02 04:48 UTC, pgaudet commented
> Can this be constrained to 'biological process'? 

I think so - I copied this from the 'regulation' DP.

2024-09-16 14:42 UTC, balhoff approved these changes

2024-09-16 17:07 UTC, merged